#获取的页面数
page: 2

#是否自动下载图片并替换图片的src
image: true

#页面的缓存时间，默认为2个小时=7200秒
#cachetime: 7200

#页面的缓存时间，默认为30分钟个小时=30*60秒=1800秒
cachetime: 1800

#禁止缓存
no_cache: false

#数据库存储文件路径
dbfile: ./website/db/content.s3db

#图片文件存储路径
img_save_path: ./website/public/imgs

#调试0 error; 1 info; 2 debug
log_level: 0